services:
  - type: web
    name: norfolkscraper
    runtime: php
    buildCommand: |
      composer install --optimize-autoloader --no-dev
      php artisan key:generate
      php artisan storage:link
      php artisan optimize
    startCommand: php artisan serve --host=0.0.0.0 --port=8080
    env: php
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        value: https://your-app-name.onrender.com
    database:
      name: your-db-name
      plan: free

  - type: worker
    name: laravel-queue-worker
    runtime: php
    buildCommand: |
      composer install --optimize-autoloader --no-dev
      php artisan key:generate
      php artisan storage:link
      php artisan optimize
    startCommand: php artisan queue:work --queue=parcels --tries=3 --timeout=300
    env: php
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        sync: true  # This makes sure APP_KEY matches the web service
      - key: APP_URL
        value: https://your-app-name.onrender.com
